[phases.setup]
nixPkgs = ["php84", "php84Extensions.pdo_sqlite", "php84Extensions.bcmath", "nodejs_20", "npm"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev --no-interaction",
    "npm install"
]

[phases.build]
cmds = [
    "npm run build",
    "php artisan optimize:clear",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "touch /app/database/database.sqlite && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
